---
  1:
    type: train
    name: Percy
    cost: 5
  2:
    type: train
    name: Caron
    cost: 5
  3:
    type: train
    name: Alstm
    cost: 5
  4:
    type: car
    name: Volvo
    cost: 20.5
  5:
    type: car
    name: Tesla
    cost: 25
  6:
    type: car
    name: Ford
    cost: 15
  7:
    type: tractor
    name: Mahindra
    cost: 10
  8:
    type: tractor
    name: Hmt-trac
    cost: 10
  9:
    type: tractor
    name: Farmtrac
    cost: 5
  10:
    type: ship
    cost: 55
    name: Annie
