#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import logging
logging.basicConfig(level=logging.DEBUG)

if __name__ == '__main__':
	try:
		from supermarket.command import main
		sys.exit(main())
	except ImportError:
		logging.error("supermarket package not found in PYTHONPATH.")
